// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlrusuupscqvrjumvmcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscnVzdXVwc2NxdnJqdW12bWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDkxNDUsImV4cCI6MjA3MDc4NTE0NX0.E69r7GEnCVBYiztOPw3LHnZXQk39GmYVltZOjVYqTBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});